# Generated by Django 4.2.23 on 2025-09-10 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LMSproject', '0002_remove_lesson_task_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
