# Generated by Django 5.2.4 on 2025-08-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSproject', '0003_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(unique=True),
        ),
    ]
