# Generated by Django 5.2.4 on 2025-08-14 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSproject', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='task',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSproject.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerForTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMSproject.task')),
            ],
        ),
    ]
