# Generated by Django 5.2.4 on 2025-08-14 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSproject', '0005_remove_lesson_task_task_answerfortask'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerfortask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
