# Generated by Django 5.2.4 on 2025-08-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSproject', '0006_answerfortask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
