# Generated by Django 5.2.4 on 2025-09-03 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSproject', '0008_alter_lesson_image_alter_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerfortask',
            name='grade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)]),
        ),
    ]
