# Generated by Django 5.2.4 on 2025-09-03 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSproject', '0009_answerfortask_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerfortask',
            name='grade',
            field=models.IntegerField(default='0', validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
    ]
